spring:
  application:
    name: esp-registry

server:
  port: ${CFG_EUREKA_PORT:8761}

eureka:
  instance:
    hostname: ${spring.cloud.client.hostname}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/