spring:
  application:
    name: esp-config
  cloud:
    config:
      server:
        git:
          uri: http://10.27.213.70/esp/esp-cloud-config.git
          searchPaths: '{application}'
          username: unknow
          password: unknow

server:
  port: ${CFG_CONFIG_PORT:8750}

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${CFG_EUREKA_HOST:${spring.cloud.client.hostname}}:${CFG_EUREKA_PORT:8761}/eureka/