spring:
  application:
    name: esp-config
  cloud:
    config:
      server:
        git:
          uri: http://10.27.213.70/esp/esp-cloud-config.git
          searchPaths: '{application}'
          username: general
          password: General@413

server:
  port: 8750

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${CFG_EUREKA_HOST:${spring.cloud.client.ip-address}}:${CFG_EUREKA_PORT:8761}/eureka/