spring:
  application:
    name: esp-config
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/riped-config?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: mysql
    type:
  profiles:
    active: jdbc
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `key`, `value` FROM properties WHERE application=? AND profile=? AND label=?
        prefix: cfg
  jpa:
    database: mysql
    show-sql: true

#  resources:
#    static-locations: classpath:/static/,classpath:/templates/
#  mvc:
#    static-path-pattern: /**
#spring.resources.chain.strategy.fixed.paths:
#  resources:
#    chain:
#      strategy:
#        content:
#          enabled: true
#        fixed:
#          paths: /static/

server:
  port: 8750

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 使用IP地址注册，默认为主机名
    preferIpAddress: true
  client:
    # 禁用Eureka服务发现客户端
#    enabled: false
    serviceUrl:
      defaultZone: http://${CFG_EUREKA_HOST:${spring.cloud.client.ip-address}}:${CFG_EUREKA_PORT:8761}/eureka/