spring:
  application:
    name: fr-config
  cloud:
    config:
      server:
        git:
          uri: file://${user.dir}/docs/config-repo
          searchPaths: '{application}'

server:
  port: 8082

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.hostname}:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"