spring:
  application:
    name: thraex-framework-fs
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/THRAEX_FS?useSSL=false
    username: root
    password: mysql
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#    default-property-inclusion: non_null

server:
  port: 8090

logging:
  level:
    org.thraex.fs.base.mapper: DEBUG
