spring:
  application:
    name: esp-business-order

server:
  port: 8093

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 使用IP地址注册，默认为主机名
    preferIpAddress: true
    metadataMap:
      zone: zone1
  client:
    availabilityZones:
      us-east-1: zone1,zone2
    serviceUrl:
      zone1: http://${spring.cloud.client.ip-address}:8761/eureka/
      zone2: http://${spring.cloud.client.ip-address}:8762/eureka/
    # 禁用Eureka服务发现客户端
#    enabled: false
#    serviceUrl:
#      defaultZone: http://${spring.cloud.client.ip-address}:8761/eureka/

app.order.name: ${spring.application.name}[THRAEX]